// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weightVectors.proto

package de.uniheidelberg.cl.softpro.sentimentclassification.scalable;

public final class WeightVectorProtos {
  private WeightVectorProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface featureVectorOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .scalable.featureVector.featureValuePair featureValue = 1;
    /**
     * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
     */
    java.util.List<de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair> 
        getFeatureValueList();
    /**
     * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
     */
    de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair getFeatureValue(int index);
    /**
     * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
     */
    int getFeatureValueCount();
    /**
     * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
     */
    java.util.List<? extends de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePairOrBuilder> 
        getFeatureValueOrBuilderList();
    /**
     * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
     */
    de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePairOrBuilder getFeatureValueOrBuilder(
        int index);

    // optional string label = 2;
    /**
     * <code>optional string label = 2;</code>
     */
    boolean hasLabel();
    /**
     * <code>optional string label = 2;</code>
     */
    java.lang.String getLabel();
    /**
     * <code>optional string label = 2;</code>
     */
    com.google.protobuf.ByteString
        getLabelBytes();
  }
  /**
   * Protobuf type {@code scalable.featureVector}
   */
  public static final class featureVector extends
      com.google.protobuf.GeneratedMessage
      implements featureVectorOrBuilder {
    // Use featureVector.newBuilder() to construct.
    private featureVector(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private featureVector(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final featureVector defaultInstance;
    public static featureVector getDefaultInstance() {
      return defaultInstance;
    }

    public featureVector getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private featureVector(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                featureValue_ = new java.util.ArrayList<de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair>();
                mutable_bitField0_ |= 0x00000001;
              }
              featureValue_.add(input.readMessage(de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              label_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          featureValue_ = java.util.Collections.unmodifiableList(featureValue_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.internal_static_scalable_featureVector_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.internal_static_scalable_featureVector_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.class, de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.Builder.class);
    }

    public static com.google.protobuf.Parser<featureVector> PARSER =
        new com.google.protobuf.AbstractParser<featureVector>() {
      public featureVector parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new featureVector(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<featureVector> getParserForType() {
      return PARSER;
    }

    public interface featureValuePairOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string featureName = 1;
      /**
       * <code>required string featureName = 1;</code>
       */
      boolean hasFeatureName();
      /**
       * <code>required string featureName = 1;</code>
       */
      java.lang.String getFeatureName();
      /**
       * <code>required string featureName = 1;</code>
       */
      com.google.protobuf.ByteString
          getFeatureNameBytes();

      // required double value = 2;
      /**
       * <code>required double value = 2;</code>
       */
      boolean hasValue();
      /**
       * <code>required double value = 2;</code>
       */
      double getValue();
    }
    /**
     * Protobuf type {@code scalable.featureVector.featureValuePair}
     */
    public static final class featureValuePair extends
        com.google.protobuf.GeneratedMessage
        implements featureValuePairOrBuilder {
      // Use featureValuePair.newBuilder() to construct.
      private featureValuePair(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private featureValuePair(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final featureValuePair defaultInstance;
      public static featureValuePair getDefaultInstance() {
        return defaultInstance;
      }

      public featureValuePair getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private featureValuePair(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                featureName_ = input.readBytes();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                value_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.internal_static_scalable_featureVector_featureValuePair_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.internal_static_scalable_featureVector_featureValuePair_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.class, de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.Builder.class);
      }

      public static com.google.protobuf.Parser<featureValuePair> PARSER =
          new com.google.protobuf.AbstractParser<featureValuePair>() {
        public featureValuePair parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new featureValuePair(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<featureValuePair> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string featureName = 1;
      public static final int FEATURENAME_FIELD_NUMBER = 1;
      private java.lang.Object featureName_;
      /**
       * <code>required string featureName = 1;</code>
       */
      public boolean hasFeatureName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string featureName = 1;</code>
       */
      public java.lang.String getFeatureName() {
        java.lang.Object ref = featureName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            featureName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string featureName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFeatureNameBytes() {
        java.lang.Object ref = featureName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          featureName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required double value = 2;
      public static final int VALUE_FIELD_NUMBER = 2;
      private double value_;
      /**
       * <code>required double value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double value = 2;</code>
       */
      public double getValue() {
        return value_;
      }

      private void initFields() {
        featureName_ = "";
        value_ = 0D;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasFeatureName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getFeatureNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, value_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getFeatureNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, value_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code scalable.featureVector.featureValuePair}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePairOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.internal_static_scalable_featureVector_featureValuePair_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.internal_static_scalable_featureVector_featureValuePair_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.class, de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.Builder.class);
        }

        // Construct using de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          featureName_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.internal_static_scalable_featureVector_featureValuePair_descriptor;
        }

        public de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair getDefaultInstanceForType() {
          return de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.getDefaultInstance();
        }

        public de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair build() {
          de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair buildPartial() {
          de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair result = new de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.featureName_ = featureName_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair) {
            return mergeFrom((de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair other) {
          if (other == de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.getDefaultInstance()) return this;
          if (other.hasFeatureName()) {
            bitField0_ |= 0x00000001;
            featureName_ = other.featureName_;
            onChanged();
          }
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasFeatureName()) {
            
            return false;
          }
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string featureName = 1;
        private java.lang.Object featureName_ = "";
        /**
         * <code>required string featureName = 1;</code>
         */
        public boolean hasFeatureName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string featureName = 1;</code>
         */
        public java.lang.String getFeatureName() {
          java.lang.Object ref = featureName_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            featureName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string featureName = 1;</code>
         */
        public com.google.protobuf.ByteString
            getFeatureNameBytes() {
          java.lang.Object ref = featureName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            featureName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string featureName = 1;</code>
         */
        public Builder setFeatureName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          featureName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string featureName = 1;</code>
         */
        public Builder clearFeatureName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          featureName_ = getDefaultInstance().getFeatureName();
          onChanged();
          return this;
        }
        /**
         * <code>required string featureName = 1;</code>
         */
        public Builder setFeatureNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          featureName_ = value;
          onChanged();
          return this;
        }

        // required double value = 2;
        private double value_ ;
        /**
         * <code>required double value = 2;</code>
         */
        public boolean hasValue() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required double value = 2;</code>
         */
        public double getValue() {
          return value_;
        }
        /**
         * <code>required double value = 2;</code>
         */
        public Builder setValue(double value) {
          bitField0_ |= 0x00000002;
          value_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double value = 2;</code>
         */
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000002);
          value_ = 0D;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:scalable.featureVector.featureValuePair)
      }

      static {
        defaultInstance = new featureValuePair(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:scalable.featureVector.featureValuePair)
    }

    private int bitField0_;
    // repeated .scalable.featureVector.featureValuePair featureValue = 1;
    public static final int FEATUREVALUE_FIELD_NUMBER = 1;
    private java.util.List<de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair> featureValue_;
    /**
     * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
     */
    public java.util.List<de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair> getFeatureValueList() {
      return featureValue_;
    }
    /**
     * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
     */
    public java.util.List<? extends de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePairOrBuilder> 
        getFeatureValueOrBuilderList() {
      return featureValue_;
    }
    /**
     * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
     */
    public int getFeatureValueCount() {
      return featureValue_.size();
    }
    /**
     * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
     */
    public de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair getFeatureValue(int index) {
      return featureValue_.get(index);
    }
    /**
     * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
     */
    public de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePairOrBuilder getFeatureValueOrBuilder(
        int index) {
      return featureValue_.get(index);
    }

    // optional string label = 2;
    public static final int LABEL_FIELD_NUMBER = 2;
    private java.lang.Object label_;
    /**
     * <code>optional string label = 2;</code>
     */
    public boolean hasLabel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string label = 2;</code>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          label_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string label = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      featureValue_ = java.util.Collections.emptyList();
      label_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getFeatureValueCount(); i++) {
        if (!getFeatureValue(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < featureValue_.size(); i++) {
        output.writeMessage(1, featureValue_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getLabelBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < featureValue_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, featureValue_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLabelBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code scalable.featureVector}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVectorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.internal_static_scalable_featureVector_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.internal_static_scalable_featureVector_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.class, de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.Builder.class);
      }

      // Construct using de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFeatureValueFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (featureValueBuilder_ == null) {
          featureValue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          featureValueBuilder_.clear();
        }
        label_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.internal_static_scalable_featureVector_descriptor;
      }

      public de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector getDefaultInstanceForType() {
        return de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.getDefaultInstance();
      }

      public de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector build() {
        de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector buildPartial() {
        de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector result = new de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (featureValueBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            featureValue_ = java.util.Collections.unmodifiableList(featureValue_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.featureValue_ = featureValue_;
        } else {
          result.featureValue_ = featureValueBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.label_ = label_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector) {
          return mergeFrom((de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector other) {
        if (other == de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.getDefaultInstance()) return this;
        if (featureValueBuilder_ == null) {
          if (!other.featureValue_.isEmpty()) {
            if (featureValue_.isEmpty()) {
              featureValue_ = other.featureValue_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFeatureValueIsMutable();
              featureValue_.addAll(other.featureValue_);
            }
            onChanged();
          }
        } else {
          if (!other.featureValue_.isEmpty()) {
            if (featureValueBuilder_.isEmpty()) {
              featureValueBuilder_.dispose();
              featureValueBuilder_ = null;
              featureValue_ = other.featureValue_;
              bitField0_ = (bitField0_ & ~0x00000001);
              featureValueBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFeatureValueFieldBuilder() : null;
            } else {
              featureValueBuilder_.addAllMessages(other.featureValue_);
            }
          }
        }
        if (other.hasLabel()) {
          bitField0_ |= 0x00000002;
          label_ = other.label_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getFeatureValueCount(); i++) {
          if (!getFeatureValue(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .scalable.featureVector.featureValuePair featureValue = 1;
      private java.util.List<de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair> featureValue_ =
        java.util.Collections.emptyList();
      private void ensureFeatureValueIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          featureValue_ = new java.util.ArrayList<de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair>(featureValue_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair, de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.Builder, de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePairOrBuilder> featureValueBuilder_;

      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public java.util.List<de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair> getFeatureValueList() {
        if (featureValueBuilder_ == null) {
          return java.util.Collections.unmodifiableList(featureValue_);
        } else {
          return featureValueBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public int getFeatureValueCount() {
        if (featureValueBuilder_ == null) {
          return featureValue_.size();
        } else {
          return featureValueBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair getFeatureValue(int index) {
        if (featureValueBuilder_ == null) {
          return featureValue_.get(index);
        } else {
          return featureValueBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public Builder setFeatureValue(
          int index, de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair value) {
        if (featureValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeatureValueIsMutable();
          featureValue_.set(index, value);
          onChanged();
        } else {
          featureValueBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public Builder setFeatureValue(
          int index, de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.Builder builderForValue) {
        if (featureValueBuilder_ == null) {
          ensureFeatureValueIsMutable();
          featureValue_.set(index, builderForValue.build());
          onChanged();
        } else {
          featureValueBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public Builder addFeatureValue(de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair value) {
        if (featureValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeatureValueIsMutable();
          featureValue_.add(value);
          onChanged();
        } else {
          featureValueBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public Builder addFeatureValue(
          int index, de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair value) {
        if (featureValueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFeatureValueIsMutable();
          featureValue_.add(index, value);
          onChanged();
        } else {
          featureValueBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public Builder addFeatureValue(
          de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.Builder builderForValue) {
        if (featureValueBuilder_ == null) {
          ensureFeatureValueIsMutable();
          featureValue_.add(builderForValue.build());
          onChanged();
        } else {
          featureValueBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public Builder addFeatureValue(
          int index, de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.Builder builderForValue) {
        if (featureValueBuilder_ == null) {
          ensureFeatureValueIsMutable();
          featureValue_.add(index, builderForValue.build());
          onChanged();
        } else {
          featureValueBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public Builder addAllFeatureValue(
          java.lang.Iterable<? extends de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair> values) {
        if (featureValueBuilder_ == null) {
          ensureFeatureValueIsMutable();
          super.addAll(values, featureValue_);
          onChanged();
        } else {
          featureValueBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public Builder clearFeatureValue() {
        if (featureValueBuilder_ == null) {
          featureValue_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          featureValueBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public Builder removeFeatureValue(int index) {
        if (featureValueBuilder_ == null) {
          ensureFeatureValueIsMutable();
          featureValue_.remove(index);
          onChanged();
        } else {
          featureValueBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.Builder getFeatureValueBuilder(
          int index) {
        return getFeatureValueFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePairOrBuilder getFeatureValueOrBuilder(
          int index) {
        if (featureValueBuilder_ == null) {
          return featureValue_.get(index);  } else {
          return featureValueBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public java.util.List<? extends de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePairOrBuilder> 
           getFeatureValueOrBuilderList() {
        if (featureValueBuilder_ != null) {
          return featureValueBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(featureValue_);
        }
      }
      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.Builder addFeatureValueBuilder() {
        return getFeatureValueFieldBuilder().addBuilder(
            de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.getDefaultInstance());
      }
      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.Builder addFeatureValueBuilder(
          int index) {
        return getFeatureValueFieldBuilder().addBuilder(
            index, de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.getDefaultInstance());
      }
      /**
       * <code>repeated .scalable.featureVector.featureValuePair featureValue = 1;</code>
       */
      public java.util.List<de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.Builder> 
           getFeatureValueBuilderList() {
        return getFeatureValueFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair, de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.Builder, de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePairOrBuilder> 
          getFeatureValueFieldBuilder() {
        if (featureValueBuilder_ == null) {
          featureValueBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair, de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePair.Builder, de.uniheidelberg.cl.softpro.sentimentclassification.scalable.WeightVectorProtos.featureVector.featureValuePairOrBuilder>(
                  featureValue_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          featureValue_ = null;
        }
        return featureValueBuilder_;
      }

      // optional string label = 2;
      private java.lang.Object label_ = "";
      /**
       * <code>optional string label = 2;</code>
       */
      public boolean hasLabel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string label = 2;</code>
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string label = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string label = 2;</code>
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 2;</code>
       */
      public Builder clearLabel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 2;</code>
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        label_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:scalable.featureVector)
    }

    static {
      defaultInstance = new featureVector(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:scalable.featureVector)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scalable_featureVector_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scalable_featureVector_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scalable_featureVector_featureValuePair_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scalable_featureVector_featureValuePair_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023weightVectors.proto\022\010scalable\"\226\001\n\rfeat" +
      "ureVector\022>\n\014featureValue\030\001 \003(\0132(.scalab" +
      "le.featureVector.featureValuePair\022\r\n\005lab" +
      "el\030\002 \001(\t\0326\n\020featureValuePair\022\023\n\013featureN" +
      "ame\030\001 \002(\t\022\r\n\005value\030\002 \002(\001BR\n<de.uniheidel" +
      "berg.cl.softpro.sentimentclassification." +
      "scalableB\022WeightVectorProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_scalable_featureVector_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_scalable_featureVector_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scalable_featureVector_descriptor,
              new java.lang.String[] { "FeatureValue", "Label", });
          internal_static_scalable_featureVector_featureValuePair_descriptor =
            internal_static_scalable_featureVector_descriptor.getNestedTypes().get(0);
          internal_static_scalable_featureVector_featureValuePair_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_scalable_featureVector_featureValuePair_descriptor,
              new java.lang.String[] { "FeatureName", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
